### PR TITLE
Update UI for v0.2 demo

### LINKED ISSUE #39: Enhance the UI
Tasks should be nicely laid out so that the user can read the information quickly.
Should reflect the deadline/start time/end time (month + day + time ), the status of completion (completed/uncompleted) and eventually if it is overdue or coming
Add colors to reflect the changes and update spacing

### PR DESCRIPTION
**Pull request by burnflare**
Resolves #39, by @fanwgwg.

Because of commit dependencies, this can only be merged after the following PRs have been merged:
- [x] #49 
- [ ] #79 
- [x] #71

### CODE REVIEW

**Comment by burnflare** [comment]
@fanwgwg Could you do a `git checkout master && git pull master && git checkout change-ui && git merge master` locally then fix the 3 conflicts?

After you manually fixed those conflicts, then do a `git add .` then `git commit` then `git push change-ui`

**Review by fanwgwg — APPROVED** [review]

**Comment by burnflare** [comment]
@fanwgwg Take a look at the [Travis logs](https://travis-ci.org/CS2103AUG2016-W11-C2/main/builds/166465867) and search for "Failed"

You'll see a bunch of things that failed in this branch such as:

```
guitests.AddCommandTest > add FAILED
    java.lang.IllegalStateException: Name not found: meet Alice Pauline
        at guitests.guihandles.TaskListPanelHandle.navigateToTask(TaskListPanelHandle.java:107)
        at guitests.AddCommandTest.assertAddSuccess(AddCommandTest.java:45)
        at guitests.AddCommandTest.add(AddCommandTest.java:34)
```

Could you investigate why it might be?

**Comment by burnflare** [comment]
@fanwgwg Tests are failing for me locally to. This is the command that travis runs:
`./gradlew clean headless allTests coverage coveralls -i`

Can you try running that script locally?

**Comment by burnflare** [comment]
Yay tests pass now :) :)

**Comment by burnflare** [comment]
@fanwgwg The one test that failed in latest build was `guitests.HelpWindowTest > openHelpWindow FAILED`. Could you look at that?

**Comment by burnflare** [comment]
@rachx @INCENDE This branch is looking good to review now

**Comment by fanwgwg** [comment]
I just checked locally by running headless, the helpwindow passes test.

**Comment by burnflare** [comment]
This PR is all green now. @fanwgwg are you confident to master this? (Don't push merge yourself, I'll help you do it because of the potential conflict issues from other branches)

**Comment by burnflare** [comment]
Passing! Yay!

**Comment by burnflare** [comment]
@fanwgwg Confident to merge yet?

**Comment by fanwgwg** [comment]
So the branch #79 doesn't matter now?

**Comment by burnflare** [comment]
@fanwgwg Ideally yes: we should re-open 79, clean it up, merge it first, then update this PR then merge it. Do you wanna quickly get that done?

**Comment by fanwgwg** [comment]
Since Rachael says that though the code in #79 works, it is quite messy, so she has rewrote some codes in another branch. Is it okay if we just merge this branch into master first?

**Comment by burnflare** [comment]
Yeah we could just merge this branch into master now (it's due time; this PR is getting very very big), then can create a new branch to fix whatever messiness we want later then PR it. @rachx thoughts?

**Comment by rachx** [comment]
Just merge then. I think we can choose to keep the new files from my existing pr later?

**Pull request merged**
