### PR TITLE
Sort help window results

### LINKED ISSUE #129: Show help command words in alphabetical order
Might want to move the getCommandWords to command word so it can used be auto correct, alias etc

### PR DESCRIPTION
**Pull request by burnflare**
Resolves #129

### CODE REVIEW

**Comment by burnflare** [comment]
@rachx please review

**Review by rachx — APPROVED** [review]

**Comment by rachx** [comment]
Might want to number the command and sort by their priority in the future e.g. add, rename, schedule, mark, unmark etc

**Comment by burnflare** [comment]
I can do that by tagging some commands as high priority commands and then sorting within high priority and low priority commands. Will do that in this PR.

Can you list which commands are "high priority"? Thanks!

**Comment by rachx** [comment]
Just leave it by name then. It is not very flexible if new commands are added too. Want to remove clear command? Since now we can delete multiple?

**Pull request merged**
