### PR TITLE
Project file cleanup

### PR DESCRIPTION
**Pull request by burnflare**
Just removing a bunch of files I think we don't need. @INCENDE please verify

### CODE REVIEW

**Comment by INCENDE** [comment]
need collate tui for collating our final finals

**Comment by burnflare** [comment]
@INCENDE you're right but we don't need it to my part of our own codebase. We don't own Collate, it lives in it's own project [here](https://github.com/collate/collate). Whoever runs collate can just download it from source, and run it themselves. Those binaries don't need to be part of our repo

**Comment by INCENDE** [comment]
Alright, so let's merge this after we've finalised our code and docs

**Comment by burnflare** [comment]
I have my own copy of Collate.jar so I'll help to generate collation even after removing these.

We might be changing docs/code even at the last 1hr to submission so waiting until Monday 11pm to removing many files in the repo might be dangerous.

**Review by INCENDE — APPROVED** [review]

**Pull request merged**
