### PR TITLE
Address GCal Flaky tests

### PR DESCRIPTION
**Pull request by burnflare**
Fixing #212

Strategies
- Removed one test
- Made test less exhaustive but removing `@Before` that initialises a fresh Google Calendar instance each time. Instead just doing Google Calendar initialisation once on class constructor
- Made 3 fake accounts and storing their credentials. Randomly picking from one of them.

### CODE REVIEW

**Comment by burnflare** [comment]
@INCENDE do review.

Problem is, no matter what this is going to cause flakiness in our tests.... There might be random times where some Travis tests will fail. The resolution then would be to click into Travis and restart the build.

**Review by INCENDE — APPROVED** [review]

**Comment by burnflare** [comment]
Not merging yet

**Comment by rachx** [comment]
@burnflare 
After I type sync on but close the window instead of accepting/rejecting, the app will crash. Can we do anything about it?

**Comment by burnflare** [comment]
@rachx close which window? The browser or the app?

**Comment by burnflare** [comment]
Investigate `GoogleJsonResponseException: 404 Not Found`

**Comment by rachx** [comment]
browser

**Comment by burnflare** [comment]
@rachx Looked at it, don't think I can do anything about it as that entire flow is handled by the Google SDK and not me.

**Comment by burnflare** [comment]
Reran tests twice, all 4 travis jobs passed. Somewhat confident, going to merge.

**Pull request merged**
