### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by INCENDE**

### CODE REVIEW

**Comment by burnflare** [comment]
@INCENDE Do you want me to help fix that conflict?

**Review by burnflare — APPROVED** [review]
Fantastic

**Comment by burnflare** [comment]
@INCENDE Shall I trust that your version of the file is the latest one and just do the merge that way? Or do you want to do a 2 way merge?

**Comment by INCENDE** [comment]
I have fixed the conflicts. Thanks @burnflare

**Pull request merged**
