### PR TITLE
Final project collation

### PR DESCRIPTION
**Pull request by burnflare**
Will only merge this after getting 3 approvals from everyone

### CODE REVIEW

**Comment by burnflare** [comment]
There is a dup file in the docs. `docs/A0133367E.md` & `docs/A013367E.md`. Please fix in the code and I'll recolate

**Comment by burnflare** [comment]
Actually nvm, I can fix that myself

**Comment by burnflare** [comment]
Ok collate fix. Everyone please verify

**Comment by rachx** [comment]
okay on my side i think

**Review by rachx — APPROVED** [review]

**Comment by fanwgwg** [comment]
Should testscript.md be included?

**Comment by burnflare** [comment]
@fanwgwg Handbook says just code, test and docs

**Review by fanwgwg — APPROVED** [review]

**Pull request merged**
