### PR TITLE
Reorganise files created by agendum

### LINKED ISSUE #55: Store .json files in a folder
At the moment it's all over the place

### PR DESCRIPTION
**Pull request by INCENDE**
Resolves #55

### CODE REVIEW

**Comment by burnflare** [comment]
Will this cause issues for existing data files? Is the saving format and location different?

Also looks like tests are failing. Click on `details` then search for "failed" to see what failed.

**Comment by INCENDE** [comment]
Nope no reformatting, just relocating.

**Comment by burnflare** [comment]
Would the relocation cause backward compatibility issues?

**Comment by INCENDE** [comment]
I doubt so. Just have to move the files into the relevant folder if you want the previous settings

**Review by burnflare — APPROVED** [review]
Alight!

**Pull request merged**
