### PR TITLE
Google Calendar Integration

### PR DESCRIPTION
**Pull request by burnflare**
Usage instructions
- `sync on` (First time, a auth screen would come up on your browser. Subsequent time this does not happen)
- `add` anything with both start and end time. This would get synced to a new "Agendum Calendar" in your Google Calendar
- `sync off` turn off syncing

Not ready for merging

### CODE REVIEW

**Comment by burnflare** [comment]
@rachx @INCENDE @fanwgwg Please test! It works as the description says in #84

**Comment by burnflare** [comment]
@INCENDE Could you test functionality and approve?

**Comment by INCENDE** [comment]
Seems to be working fine. Are you going to add more tests to increase the coverage though? @burnflare

**Comment by burnflare** [comment]
This latest commit is pretty much all I can do. Added full coverage to all the new files except for `SyncProviderGoogle`. This one is hard to test because of its dependency of actually exchange OAuth tokens with Google..

**Comment by burnflare** [comment]
I just thought of a way to test the Google class! Will work on it.

**Comment by burnflare** [comment]
@INCENDE There you go! Managed to test the GoogleCalendar files. 92% now

**Review by INCENDE — APPROVED** [review]
Looks good

**Pull request merged**
