### PR TITLE
Midnight time bug

### LINKED ISSUE #87: Events not properly registering accross midnight
image

It should be wed 10pm to  thursday 5am

`[USER COMMAND][add hi from 10pm to 5am]`

### PR DESCRIPTION
**Pull request by burnflare**
This is the actual PR that's going into master
Fixes #87

Originally if today is Monday and you input `add test event from Sunday 5pm to 8pm` it will process start time next Sunday 5pm and end time previous Monday 8pm.

Now when you do `add test event from Sunday 5pm to 8pm`, it will do start time next Sunday 5pm and end time next Sunday 8pm

### CODE REVIEW

**Comment by burnflare** [comment]
@rachx please review

**Comment by burnflare** [comment]
This fixes #78 too

**Comment by burnflare** [comment]
@coveralls will no longer leave comments on PRs now, turned it off. That was too irritating.

**Comment by rachx** [comment]
Can you move it somewhere so it will work for re-scheduling too?
Maybe the HashMap etc can be in the DateTimeParser and ensure that end time is after start time

**Comment by burnflare** [comment]
Good point, it could be the objective of DateTimerParser to return the “right” end time all the time. I’ll do that, thanks.

**Comment by burnflare** [comment]
@rachx Ready for re-review

**Review by rachx — APPROVED** [review]

**Comment by burnflare** [comment]
Good point, it could be the objective of DateTimerParser to return the “right” end time all the time. I’ll do that, thanks.

**Pull request merged**
