### PR TITLE
Some ui enhancement

### PR DESCRIPTION
**Pull request by fanwgwg**
- Account for tasks with long names and allow list cell to resize according to the length of task names/time details, and allow more tasks in one panel #161 
- Show message after the `find` command and use `ESC` as shortcut key to go back to normal state #158 
- Set default window size to be full screen #162 
- Fix the max width of helpwindow and result pop up windows to avoid issues caused by resolutions on different computers
- Refactor ui code to have some inheritance and update ui diagrams

### CODE REVIEW

**Comment by burnflare** [comment]
untitled

This looks good! Can we try left aligning the text?

**Comment by burnflare** [comment]
Feedback: When I hit `Esc` on the HelpPopup, my keyboard should automatically focus on the command box. Now I need to manually click on the command box after dismissing the help popup

**Comment by fanwgwg** [comment]
Just updated! @burnflare

**Comment by rachx** [comment]
Can we use F5 in the command box to make the help window open as well?

**Comment by burnflare** [comment]
Why F5?

**Comment by rachx** [comment]
F5 works on the main window. Doesn't work within the command box. Alternatively, change both

**Comment by rachx** [comment]
Oh wait, I just remember there is CTRL + H. probably should change the docs and help on the top bar

**Comment by fanwgwg** [comment]
@burnflare Previously I trie to set the hot key to be `ctrl` or `alt` combining some other keys, but it turns out that these keys all fail on travis, only the function key works there, so I change it to F5. @rachx The top bar does not need to change right? Cuz F5 is still used to open the help window, but the other one is used for switching between help window and main window, if the help window is already open. Btw, since the helpwindow final implementation hasn't been confirmed, so no worries about whatever is on the top bar right now.

**Comment by rachx** [comment]
@fanwgwg Nicely done :) Can merge if everything pass.
I am not sure how to get the help window to show consistently though

**Review by rachx — APPROVED** [review]

**Comment by burnflare** [comment]
@fanwgwg  I realised now there's a new bug now:
When the message popup disappear, the command box automatically gets keyboard focus, which is great except....... what if I type a command then immediately switch to another app? What happens is that after a few seconds when the message window disappear, I'm force switched back into Agendum. 
1. Type a command
2. Hit enter
3. Quickly change to another app.
4. Wait a few seconds and you'll be forced back into Agendum.

**Comment by fanwgwg** [comment]
@burnflare Just updated in the task highlighting branch #179 minutes ago, fix the issue that main window requests focus automatically!

**Comment by burnflare** [comment]
Wow, thanks!

**Pull request merged**
