### PR TITLE
Task highlighting

### PR DESCRIPTION
**Pull request by fanwgwg**
- Highlight the task(s) just added/marked/unmarked/renamed/scheduled #160 
- Highlight existing tasks that already exist when adding some duplicates
- Add short key `ctrl`+`z` for undo #181 
- Show completed time for completed tasks #184 
- Remove the placeholder of time for floating tasks #183 
- Change the shortcut key of opening of help window from F5 to `ctrl`+`H`

### CODE REVIEW

**Comment by fanwgwg** [comment]
Gui tests fail, going to investigate on it.

**Comment by burnflare** [comment]
@fanwgwg Mind attaching screenshots here of how the new elements look like?

**Comment by fanwgwg** [comment]
2016-10-31 at 20 13
This is how it looks like after the changes. @burnflare Is this fine?

**Comment by burnflare** [comment]
Ooo nice, variable cell heights. If I have a title that's 2 lines long will it be taller too?

**Comment by fanwgwg** [comment]
Yup it will resize automatically!

**Comment by rachx** [comment]
Actually, it is showing the last updated time instead of the completion time.
So if you rename a completed task, the time will changed as well >.<
I still think it will be useful to show the time of events/deadlines that have passed

**Comment by rachx** [comment]
Fixes #117, #181, #183, #184
Revise #160 after update-model

**Comment by burnflare** [comment]
@rachx @fanwgwg Is this good to go in?

**Review by rachx — APPROVED** [review]

**Pull request merged**
