### PR TITLE
Helpwindow integration

### PR DESCRIPTION
**Pull request by fanwgwg**
- Integrate helpwindow into mainwindow so that it doesn't pop up as a new window.

- No change to all the previous shortcuts, including `ctrl-H` to open/switch back and  `ESC` to close.

Screenshot: 
2016-11-01 at 22 25

@burnflare @INCENDE @rachx any comments?

### CODE REVIEW

**Comment by burnflare** [comment]
Nice, does it make sense to do this for the normal result popups also?

**Comment by INCENDE** [comment]
Cool

**Comment by fanwgwg** [comment]
haha rachael asked about the same thing. The reason why I didn't make result pop up window inside the main window is that I feel it quite annoying to see the ui(those three columns) shifting updown after each command entered. Currently in javafx there is no way to do something like overlay, there needs to be a placeholder so that it can be reflected on ui, but our ui doesn't seem to have an empty place to fill a placeholder in.

**Comment by rachx** [comment]
Nice! So if I want to schedule a task, I refer to the help window, start typing and Ctrl + H to switch back to the task list to get the index?

**Comment by fanwgwg** [comment]
yes! Actually after opening the help window, any command you type, except for `help` itself, the window will just be switched to how it should look like after that command is executed.

**Review by rachx — APPROVED** [review]

**Pull request merged**
