### PR TITLE
Fix test scripts

### PR DESCRIPTION
**Pull request by rachx**

### CODE REVIEW

**Comment by rachx** [comment]
@burnflare can you fix the links in about us page to the relevant user guide sections here?

**Comment by burnflare** [comment]
Working on it

**Review by fanwgwg — APPROVED** [review]
Good!

**Review by burnflare — APPROVED** [review]

**Comment by rachx** [comment]
@burnflare 
square brackets for collate are intentional
it should look like this
https://github.com/nus-cs2103/website/blob/master/contents/AboutUs.md

remember to add our userid too

**Comment by burnflare** [comment]
@rachx Thanks, updating to that format

**Comment by burnflare** [comment]
Brought the brackets back

**Comment by rachx** [comment]
See last PR. I thought it is bad that we are giving ids when the ids will change after any updates. But we can't give specific names

**Comment by burnflare** [comment]
Yup that's a good change

**Pull request merged**
