### PR TITLE
Ui enhancements

### LINKED ISSUE #193: Improve UI Color coordination
- Lighter orange for do it soon
- Blue highlight on blue highlight is weird
- Deleting a huge number of items, notificatons is too long
- Remove seconds from time display
- "Showing search results" should be flush with command box

### PR DESCRIPTION
**Pull request by fanwgwg**
- Changed some colors
- Inline find command message
- Remove seconds in the status bar
- Set the max height/width of pop up window to be main window height/width
- Added some shortcut key gui test
- Fix the bug during demo that ctrl-H doesn't go back to main window

Fixes #193

### CODE REVIEW

**Comment by burnflare** [comment]
@fanwgwg Just fyi there's no need to make a PR to run Travis. Travis is always running on all pushed branches. You can see their build status here https://travis-ci.org/CS2103AUG2016-W11-C2/main/branches

**Comment by fanwgwg** [comment]
hahah just realised that so I close it for now

**Comment by burnflare** [comment]
@fanwgwg Is this ready to review? If so, can attach screenshot?

**Comment by fanwgwg** [comment]
screen shot 2016-11-04 at 23 01 37 This is the updated color scheme, is it fine? @burnflare @INCENDE @rachx

**Comment by rachx** [comment]
When i pulled the branch, it looks like
image
The overdue color is not very obvious

@fanwgwg : I think we can use the color scheme of the screenshot you took 👍 . Change and merge

**Review by rachx — APPROVED** [review]

**Comment by burnflare** [comment]
@fanwgwg was the change made before merging?

**Comment by fanwgwg** [comment]
I don't think there is any change needed, cuz I've already made the changes before rachael asked about, so it could be that she didn't pull the latest changes?

**Pull request merged**
