### PR TITLE
Load command

### PR DESCRIPTION
**Pull request by INCENDE**

### CODE REVIEW

**Review by burnflare — CHANGES_REQUESTED** [review]
Why are there changes to the markdown guides in this PR?

Otherwise, this PR looks ok @INCENDE

**Comment by burnflare** [comment]
Why closing?

**Comment by INCENDE** [comment]
Well it's using MainApp to reload the model, which is kinda wrong. Going to try another way later on

**Comment by burnflare** [comment]
Cool!

**Pull request closed without merging**
