### PR TITLE
Improve UI snappiness

### PR DESCRIPTION
**Pull request by burnflare**
This is my attempt at solving #134

### CODE REVIEW

**Comment by burnflare** [comment]
@fanwgwg I just searched the codebase for `sleep(` and reduced whatever sleeps I thought was unreasonably long. And this made a big difference. The UI feels much much more snappy now. Could you verify that my changes are good and didn't break anything inadvertently?

Also if you have any UI performance improvements, push them to this branch too.

**Comment by fanwgwg** [comment]
Not sure though. Let's wait and see the travis result, cuz some of the sleep was because of the slow gui test. Not sure how it goes after changing them.

**Comment by burnflare** [comment]
Valid point. If travis is the only person who's complaining about "fast UI", then there's a way to detect programatically if we're in `headless` mode. Then we can set sleep times to be to its old slow speed in `headless` mode by default to its fast speed in normal mode.

Let's not set sleep to be slow just for travis. In this PR let's collect all the time improvements we can get for Usability first, then set conditions for travis when necessary. So, feel free to push more Usability speed ups if you find them

**Comment by burnflare** [comment]
Wow tests pass! @fanwgwg bring on more speedups!

**Comment by fanwgwg** [comment]
I just found that there is something going wrong with the ui after the speedup, especially after adding many many tasks, and then keep marking some of them, like mark 1, mark 2, mark 5, mark 1-10, mark 2-4....then the completed task panel cannot handle already. It will not update anything.

**Comment by burnflare** [comment]
@fanwgwg I had some issues but after deleting `config.json`, `preferences.json` and `todolist.log` from the main folder then relaunching the app made things better. Wanna try doing that too and still see if the app is wonky?

**Comment by burnflare** [comment]
@fanwgwg Could you investigate this again?

**Comment by burnflare** [comment]
@fanwgwg What do you say about this PR? Drop it?

**Comment by fanwgwg** [comment]
Can just merge in?

**Comment by burnflare** [comment]
I thought you had some issues with it?

**Comment by fanwgwg** [comment]
Okay...But I realized that these handles.java are all for gui tests, and they shouldn't have effects on the ui itself?

**Pull request closed without merging**
